theme = "dracula"

[cursor]
shape = "beam"

[window]
opacity = 0.9

padding-x = 16
padding-y = [12, 12]

[fonts]
family = "FiraCode Nerd Font Mono"
size = 18

[fonts.regular]
weight = 600

[keyboard]
use-kitty-keyboard-protocol = true

[navigation]
mode = "Plain"
use-current-path = true
