theme = "dracula"
confirm-before-quit = false
padding-x = 24
padding-y = [16, 16]

[cursor]
shape = "beam"

[window]
opacity = 0.9

[fonts]
family = "FiraCode Nerd Font Mono"
size = 18

[fonts.regular]
weight = 500

[keyboard]
use-kitty-keyboard-protocol = true

[navigation]
mode = "BottomTab"
use-current-path = true
